# Writes the GPU pack table that is compiled into fllama
# (docs/ADR_004_DESKTOP_GPU_BACKENDS.md, D13).
#
# cmake -DOUT_CPP=<file> -DOUT_JSON=<file> -DFILE_COUNT=<n>
#       -DFILE_<i>_PACK=<pack> -DFILE_<i>_PATH=<library>
#       -DFILE_<i>_URL=<gzipped release asset> -P gpu_packs.cmake
#
# A URL may contain @FILE@. It is replaced with the file name of the file.
#
# A file that another build published (the CUDA pack, ADR 004 D16) has
# -DFILE_<i>_NAME=<file name> and -DFILE_<i>_SHA256=<hex> instead of
# FILE_<i>_PATH. Its JSON entry has "external":true.
#
# OUT_CPP defines the table that src/fllama_gpu_packs.h declares. OUT_JSON
# lists the same files for hook/build.dart, which publishes the files built
# here as packs instead of code assets.
set(entries "")
set(json "[")
if(FILE_COUNT GREATER 0)
  math(EXPR last "${FILE_COUNT} - 1")
  foreach(i RANGE ${last})
    set(pack "${FILE_${i}_PACK}")
    set(path "${FILE_${i}_PATH}")
    set(url "${FILE_${i}_URL}")
    if(path)
      if(NOT EXISTS "${path}")
        message(FATAL_ERROR "GPU pack file is missing: ${path}")
      endif()
      get_filename_component(name "${path}" NAME)
      file(SHA256 "${path}" sha256)
      set(external "false")
    else()
      set(name "${FILE_${i}_NAME}")
      set(sha256 "${FILE_${i}_SHA256}")
      set(external "true")
      if(NOT name MATCHES "^[A-Za-z0-9._+-]+$")
        message(FATAL_ERROR "GPU pack file ${i} has no valid name: ${name}")
      endif()
      if(NOT sha256 MATCHES "^[0-9a-f]+$")
        message(FATAL_ERROR "GPU pack file ${name} has no valid SHA-256: ${sha256}")
      endif()
      string(LENGTH "${sha256}" length)
      if(NOT length EQUAL 64)
        message(FATAL_ERROR "GPU pack file ${name} has no valid SHA-256: ${sha256}")
      endif()
    endif()
    string(REPLACE "@FILE@" "${name}" url "${url}")
    if(NOT url MATCHES "^https://[^\"\\]+$")
      message(FATAL_ERROR "GPU pack file ${name} has no valid URL: ${url}")
    endif()
    string(APPEND entries
      "    {\"${pack}\", \"${name}\", \"${sha256}\", \"${url}\"},\n")
    if(i GREATER 0)
      string(APPEND json ",")
    endif()
    string(APPEND json
      "{\"pack\":\"${pack}\",\"name\":\"${name}\",\"sha256\":\"${sha256}\",\"url\":\"${url}\",\"external\":${external}}")
  endforeach()
else()
  set(entries "    {nullptr, nullptr, nullptr, nullptr},\n")
endif()
string(APPEND json "]")

set(cpp "// Generated by src/cmake/gpu_packs.cmake. Do not edit.
#include \"fllama_gpu_packs.h\"

const FllamaGpuPackFile kFllamaGpuPackFiles[] = {
${entries}};
const size_t kFllamaGpuPackFileCount = ${FILE_COUNT};
")

# Write only on change, so an unchanged table does not relink fllama.
foreach(pair "OUT_CPP;cpp" "OUT_JSON;json")
  list(GET pair 0 out_var)
  list(GET pair 1 content_var)
  set(old "")
  if(EXISTS "${${out_var}}")
    file(READ "${${out_var}}" old)
  endif()
  if(NOT old STREQUAL "${${content_var}}")
    file(WRITE "${${out_var}}" "${${content_var}}")
  endif()
endforeach()
