# Writes the GPU pack table that is compiled into fllama
# (docs/ADR_004_DESKTOP_GPU_BACKENDS.md, D13).
#
# cmake -DOUT_CPP=<file> -DOUT_JSON=<file> -DFILE_COUNT=<n>
#       -DFILE_<i>_PACK=<pack> -DFILE_<i>_PATH=<library> -P gpu_packs.cmake
#
# OUT_CPP defines the table that src/fllama_gpu_packs.h declares. OUT_JSON
# lists the same files for hook/build.dart, which publishes them as packs
# instead of code assets.
set(entries "")
set(json "[")
if(FILE_COUNT GREATER 0)
  math(EXPR last "${FILE_COUNT} - 1")
  foreach(i RANGE ${last})
    set(pack "${FILE_${i}_PACK}")
    set(path "${FILE_${i}_PATH}")
    if(NOT EXISTS "${path}")
      message(FATAL_ERROR "GPU pack file is missing: ${path}")
    endif()
    file(SHA256 "${path}" sha256)
    get_filename_component(name "${path}" NAME)
    string(APPEND entries "    {\"${pack}\", \"${name}\", \"${sha256}\"},\n")
    if(i GREATER 0)
      string(APPEND json ",")
    endif()
    string(APPEND json
      "{\"pack\":\"${pack}\",\"name\":\"${name}\",\"sha256\":\"${sha256}\"}")
  endforeach()
else()
  set(entries "    {nullptr, nullptr, nullptr},\n")
endif()
string(APPEND json "]")

set(cpp "// Generated by src/cmake/gpu_packs.cmake. Do not edit.
#include \"fllama_gpu_packs.h\"

const FllamaGpuPackFile kFllamaGpuPackFiles[] = {
${entries}};
const size_t kFllamaGpuPackFileCount = ${FILE_COUNT};
")

# Write only on change, so an unchanged table does not relink fllama.
foreach(pair "OUT_CPP;cpp" "OUT_JSON;json")
  list(GET pair 0 out_var)
  list(GET pair 1 content_var)
  set(old "")
  if(EXISTS "${${out_var}}")
    file(READ "${${out_var}}" old)
  endif()
  if(NOT old STREQUAL "${${content_var}}")
    file(WRITE "${${out_var}}" "${${content_var}}")
  endif()
endforeach()
