# CUDA compiler launcher: cmake -P time_cuda.cmake -- <nvcc> <arguments>.
# Each object gets separate timing files, so parallel compilers never append
# to the same CSV. nvcc --time records compiler phases in milliseconds.
set(args "")
set(object "")
set(next_is_object FALSE)
math(EXPR last "${CMAKE_ARGC} - 1")
foreach(i RANGE 4 ${last})
  set(arg "${CMAKE_ARGV${i}}")
  list(APPEND args "${arg}")
  if(next_is_object)
    set(object "${arg}")
    set(next_is_object FALSE)
  elseif(arg STREQUAL "-o" OR arg STREQUAL "--output-file")
    set(next_is_object TRUE)
  elseif(arg MATCHES "^--output-file=(.+)$")
    set(object "${CMAKE_MATCH_1}")
  endif()
endforeach()
if(object STREQUAL "")
  message(FATAL_ERROR "CUDA timing launcher requires an output object (-o)")
endif()
get_filename_component(object "${object}" ABSOLUTE)
get_filename_component(object_dir "${object}" DIRECTORY)
file(MAKE_DIRECTORY "${object_dir}")
# --time appends; remove timings from any previous compilation of this object.
file(REMOVE "${object}.nvcc-timing.csv" "${object}.nvcc-wall-seconds")
list(APPEND args "--time=${object}.nvcc-timing.csv")
string(TIMESTAMP started "%s" UTC)
execute_process(COMMAND ${args} RESULT_VARIABLE result)
string(TIMESTAMP finished "%s" UTC)
math(EXPR elapsed "${finished} - ${started}")
file(WRITE "${object}.nvcc-wall-seconds" "${elapsed}\n")
if(NOT result STREQUAL "0")
  message(FATAL_ERROR "CUDA compiler failed (${result}); timings saved for ${object}")
endif()
