name: "Windows - Setup OpenVINO Toolkit"
description: "Setup OpenVINO Toolkit for Windows"
inputs:
  path:
    description: "Installation path"
    required: true
  version_major:
    description: "OpenVINO major version (e.g., 2026.2)"
    required: true
  version_full:
    description: "OpenVINO full version"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download and extract OpenVINO Runtime
      shell: powershell
      run: |
        $url = "https://storage.openvinotoolkit.org/repositories/openvino/packages/${{ inputs.version_major }}/windows/openvino_toolkit_windows_${{ inputs.version_full }}_x86_64.zip"
        $out = "openvino.zip"
        Invoke-WebRequest -Uri $url -OutFile $out
        Expand-Archive -Path $out -DestinationPath ${{ inputs.path }} -Force
        Remove-Item $out
