export const action = {
    LOAD: 0,
    INITIALIZED: 1,
    INFERENCE: 2,
    INFERENCE_CALLBACK: 3,
    TOKENIZE: 4,
    TOKENIZE_CALLBACK: 5,
    GET_CHAT_TEMPLATE: 6,
    GET_CHAT_TEMPLATE_CALLBACK: 7,
    GET_EOS_TOKEN: 8,
    GET_EOS_TOKEN_CALLBACK: 9,
    INFERENCE_ID_CALLBACK: 10,
    INFERENCE_CANCEL: 11,
};