export const action = {
    LOAD: 0,
    INITIALIZED: 1,
    INFERENCE: 2,
    INFERENCE_CALLBACK: 3,
    TOKENIZE: 4,
    TOKENIZE_CALLBACK: 5,
    GET_CHAT_TEMPLATE: 6,
    GET_CHAT_TEMPLATE_CALLBACK: 7,
    RUN_COMPLETED: 8,
    ERROR: 9
};